-- =============================================================
-- V13: 택배 요금 구간표 기준정보 + 박스 자체 무게
--   편성 목적함수를 "박스 수 최소"에서 "총 배송비 최소"로 바꾸기 위한 기준정보다.
--   배송단위 1개의 요금은 세 변의 합 구간과 무게 구간 중 높은 쪽으로 정해진다.
-- =============================================================

-- V2__seed.sql / V12 를 고치지 않는 이유: 이미 적용된 DB 는 체크섬이 어긋나 기동이 막힌다.

CREATE TABLE shipping_rate_tier (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(20)   NOT NULL,
    -- 구간 순서. 세변합·무게 중 높은 쪽 구간을 고를 때의 비교 기준이고,
    -- 요금이 동률인 구간끼리도 순서가 어긋나지 않도록 별도 컬럼으로 둔다.
    rank          INT           NOT NULL UNIQUE,
    max_sum_cm    DECIMAL(6, 1) NOT NULL,
    max_weight_kg DECIMAL(6, 3) NOT NULL,
    -- 요금 미확정 구간을 표현할 수 있게 NULL 을 허용한다. seed 5행은 전부 값이 있다.
    price_krw     INT
);

-- CJ대한통운 표준운임(2024) 동일권역 기준. 아래 두 출처의 비교표에서 옮겼고,
-- CJ 공식 페이지는 접속 실패로 대조하지 못했다 — 2026 최신표로 재확인 필요.
--   https://guide-kr.fassto.ai/d4204e29-29fd-4e91-9b64-3784764a4fc2
--   https://www.cjlogistics.com/ko/utility/parcel-price  (미대조)
--   https://smartpacker.kr/guide/postbox-size-guide/     (우체국 30kg 구간 참고)
INSERT INTO shipping_rate_tier (name, rank, max_sum_cm, max_weight_kg, price_krw) VALUES
    ('극소형', 1,  80.0,  2.000, 5000),
    ('소형',   2, 100.0,  5.000, 6000),
    ('중형',   3, 120.0, 10.000, 7000),
    ('대형',   4, 140.0, 15.000, 8000),
    ('특대형', 5, 160.0, 20.000, 9000);

-- 박스 자체 무게. 배송단위 총무게 = Σ상품 무게 + 이 값이다.
-- 0.0 은 실측하지 않았다는 뜻의 잠정값 — 박스별 실측이 들어오면 이 컬럼만 채우면 된다.
ALTER TABLE box_type ADD COLUMN tare_weight_kg DECIMAL(6, 3) NOT NULL DEFAULT 0;
