-- =============================================================
-- V1: full schema — docs/03-erd.md (ERD v0.3), 16 tables
-- Units: length cm, weight kg (D-03)
-- =============================================================

-- 2. 상품 · 마스터 · 분류 --------------------------------------

CREATE TABLE category (
    code        VARCHAR(20)  PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    level       VARCHAR(10)  NOT NULL CHECK (level IN ('LARGE', 'MEDIUM')),
    parent_code VARCHAR(20)  REFERENCES category (code)
);

CREATE TABLE korean_net_master (
    gtin                 CHAR(13)     PRIMARY KEY,
    product_name         VARCHAR(200) NOT NULL,
    medium_category_code VARCHAR(20)  NOT NULL REFERENCES category (code),
    image_url            VARCHAR(500),
    batch_id             VARCHAR(50)  NOT NULL,
    imported_at          TIMESTAMP    NOT NULL
);

CREATE TABLE product (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gtin                 CHAR(13)     NOT NULL UNIQUE,
    name                 VARCHAR(200) NOT NULL,
    medium_category_code VARCHAR(20)  NOT NULL REFERENCES category (code),
    image_url            VARCHAR(500) NOT NULL,
    source               VARCHAR(10)  NOT NULL CHECK (source IN ('MASTER', 'MANUAL')),
    width_cm             DECIMAL(5, 1),
    length_cm            DECIMAL(5, 1),
    height_cm            DECIMAL(5, 1),
    -- 시연에서는 저울 하드웨어 대신 이 사전 등록값을 조회해 반환한다 (D-10)
    weight_kg            DECIMAL(6, 3),
    dim_status           VARCHAR(10)  NOT NULL DEFAULT 'NONE' CHECK (dim_status IN ('NONE', 'CONFIRMED')),
    dim_method           VARCHAR(10)  CHECK (dim_method IN ('INFERRED', 'MANUAL')),
    is_refrigerate       BOOLEAN      NOT NULL DEFAULT FALSE,
    is_fragile           BOOLEAN      NOT NULL DEFAULT FALSE,
    is_irregular         BOOLEAN      NOT NULL DEFAULT FALSE,
    stock_qty            INT          NOT NULL DEFAULT 0,
    created_at           TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE category_attribute_map (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medium_category_code VARCHAR(20) NOT NULL UNIQUE REFERENCES category (code),
    default_refrigerate  BOOLEAN     NOT NULL,
    default_fragile      BOOLEAN     NOT NULL,
    default_irregular    BOOLEAN     NOT NULL
);

-- 3. 측정 (입고 촬영/추론) -------------------------------------

CREATE TABLE measurement_session (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT       NOT NULL REFERENCES product (id),
    status              VARCHAR(15)  NOT NULL
        CHECK (status IN ('INFERRED', 'MEASURE_FAILED', 'CONFIRMED', 'DISCARDED')),
    inferred_width_cm   DECIMAL(5, 1),
    inferred_length_cm  DECIMAL(5, 1),
    inferred_height_cm  DECIMAL(5, 1),
    measured_weight_kg  DECIMAL(6, 3),
    confidence          DECIMAL(4, 3),
    gate_passed         BOOLEAN      NOT NULL,
    gate_fail_reasons   JSONB,
    confirm_method      VARCHAR(10)  CHECK (confirm_method IN ('APPROVE', 'MANUAL')),
    confirmed_width_cm  DECIMAL(6, 1),
    confirmed_length_cm DECIMAL(6, 1),
    confirmed_height_cm DECIMAL(6, 1),
    confirmed_weight_kg DECIMAL(7, 3),
    created_at          TIMESTAMP    NOT NULL DEFAULT now(),
    confirmed_at        TIMESTAMP
);

CREATE TABLE measurement_image (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT       NOT NULL REFERENCES measurement_session (id),
    camera_no  SMALLINT     NOT NULL CHECK (camera_no BETWEEN 1 AND 3),
    file_path  VARCHAR(500) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT now(),
    UNIQUE (session_id, camera_no)
);

-- 4. 재고 -------------------------------------------------------

CREATE TABLE inventory_tx (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT      NOT NULL REFERENCES product (id),
    tx_type    VARCHAR(20) NOT NULL CHECK (tx_type IN ('INBOUND', 'OUTBOUND_PACKED', 'ADJUST')),
    qty_delta  INT         NOT NULL,
    ref_type   VARCHAR(50),
    ref_id     BIGINT,
    created_at TIMESTAMP   NOT NULL DEFAULT now()
);

-- 5. 출고 -------------------------------------------------------

CREATE TABLE region (
    code VARCHAR(20) PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE line (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    region_code VARCHAR(20) NOT NULL REFERENCES region (code),
    status      VARCHAR(10) NOT NULL CHECK (status IN ('ACTIVE', 'PAUSED'))
);

CREATE TABLE orders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no  VARCHAR(50) NOT NULL UNIQUE,
    region_code VARCHAR(20) NOT NULL REFERENCES region (code),
    batch_id    VARCHAR(50) NOT NULL,
    status      VARCHAR(15) NOT NULL
        CHECK (status IN ('RECEIVED', 'ALLOCATED', 'IN_PACKING', 'PACKED', 'LOADED')),
    ordered_at  TIMESTAMP   NOT NULL,
    created_at  TIMESTAMP   NOT NULL DEFAULT now()
);

CREATE TABLE order_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT NOT NULL REFERENCES orders (id),
    product_id BIGINT NOT NULL REFERENCES product (id),
    qty        INT    NOT NULL
);

CREATE TABLE box_type (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(50)  NOT NULL,
    inner_width_cm  DECIMAL(6, 1) NOT NULL,
    inner_length_cm DECIMAL(6, 1) NOT NULL,
    inner_height_cm DECIMAL(6, 1) NOT NULL,
    stock_qty       INT          NOT NULL
);

CREATE TABLE shipment (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id           BIGINT      NOT NULL REFERENCES orders (id),
    seq_no             INT         NOT NULL,
    line_id            BIGINT      NOT NULL REFERENCES line (id),
    recommended_box_id BIGINT      NOT NULL REFERENCES box_type (id),
    -- NULL = 추천 그대로. 값 존재 = 오버라이드 — 재검수 큐의 유일한 진입 데이터라 보존 필수
    final_box_id       BIGINT      REFERENCES box_type (id),
    filler_recommended BOOLEAN     NOT NULL,
    status             VARCHAR(15) NOT NULL
        CHECK (status IN ('PLANNED', 'TOTE_ASSIGNED', 'PACKING', 'PACKED', 'LOADED')),
    packed_at          TIMESTAMP,
    created_at         TIMESTAMP   NOT NULL DEFAULT now(),
    UNIQUE (order_id, seq_no)
);

CREATE TABLE shipment_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT NOT NULL REFERENCES shipment (id),
    product_id  BIGINT NOT NULL REFERENCES product (id),
    qty         INT    NOT NULL
);

CREATE TABLE tote (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode VARCHAR(50) NOT NULL UNIQUE,
    status  VARCHAR(10) NOT NULL CHECK (status IN ('IDLE', 'ASSIGNED'))
);

CREATE TABLE tote_assignment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tote_id     BIGINT    NOT NULL REFERENCES tote (id),
    shipment_id BIGINT    NOT NULL REFERENCES shipment (id),
    assigned_at TIMESTAMP NOT NULL DEFAULT now(),
    released_at TIMESTAMP
);

-- 토트당 활성 할당 1개, shipment당 활성 할당 1개 (docs/03 §5)
CREATE UNIQUE INDEX ux_tote_assignment_active_tote
    ON tote_assignment (tote_id) WHERE released_at IS NULL;
CREATE UNIQUE INDEX ux_tote_assignment_active_shipment
    ON tote_assignment (shipment_id) WHERE released_at IS NULL;

-- 조회 경로 인덱스
CREATE INDEX ix_product_medium_category ON product (medium_category_code);
CREATE INDEX ix_measurement_session_product ON measurement_session (product_id);
CREATE INDEX ix_inventory_tx_product ON inventory_tx (product_id);
CREATE INDEX ix_order_item_order ON order_item (order_id);
CREATE INDEX ix_shipment_order ON shipment (order_id);
CREATE INDEX ix_shipment_line_status ON shipment (line_id, status);
CREATE INDEX ix_shipment_item_shipment ON shipment_item (shipment_id);
