-- =============================================================
-- V3: 시연 데이터 서브시스템 (docs/demo-subsystem-spec.md §3)
-- 시연 전용 테이블. 운영 스키마와 이름으로 분리한다.
-- =============================================================

-- 데모 상품 — 풀 구분과 정답 치수. P1의 추론 클라이언트가 촬영 시 이 행을 읽는다.
CREATE TABLE demo_product (
    gtin         CHAR(13)      PRIMARY KEY REFERENCES product (gtin),
    pool         VARCHAR(10)   NOT NULL CHECK (pool IN ('INBOUND', 'OUTBOUND')),
    gt_width_cm  DECIMAL(5, 1) NOT NULL,
    gt_length_cm DECIMAL(5, 1) NOT NULL,
    gt_height_cm DECIMAL(5, 1) NOT NULL,
    image_dir    VARCHAR(200)
);

-- 출고지시 대기열 — 런마다 배치를 순서대로 담아두고 하나씩 꺼내 접수한다.
-- released_at이 NULL인 행이 아직 투입되지 않은 배치다.
CREATE TABLE demo_order_queue (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id      VARCHAR(20) NOT NULL,
    seq         INT         NOT NULL,
    batch_json  JSONB       NOT NULL,
    released_at TIMESTAMP
);

-- 한 런 안에서 배치 순번은 유일하다 — 같은 배치가 두 번 적재되면 투입 순서가 무너진다
CREATE UNIQUE INDEX ux_demo_order_queue_run_seq ON demo_order_queue (run_id, seq);
